import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  exclude: [],
  include: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  outdir: "styled-system",
  globalVars: {
    'sidebar-width': { value: '22.4rem' },
  },
  theme: {
    tokens: {
      radii: {
        sm: { value: '0.4rem' },
        md: { value: '0.8rem' },
        lg: { value: '1.2rem' },
        xl: { value: '1.6rem' },
      },
      colors: {
        white: { value: '#FFFFFF' },
        'red.600': { value: '#F43F5E' },
        'green.50': { value: '#F0FDF4' },
        'green.100': { value: '#DCFCE7' },
        'green.200': { value: '#BBF7D0' },
        'green.300': { value: '#86EFAC' },
        'green.400': { value: '#4ADE80' },
        'green.500': { value: '#22C55E' },
        'green.600': { value: '#16A34A' },
        'green.700': { value: '#15803D' },
        'green.800': { value: '#166534' },
        'green.900': { value: '#14532D' },
        'green.950': { value: '#052E16' },
        'slate.50': { value: '#F8FAFC' },
        'slate.100': { value: '#F1F5F9' },
        'slate.200': { value: '#E2E8F0' },
        'slate.300': { value: '#CBD5E1' },
        'slate.400': { value: '#94A3B8' },
        'slate.500': { value: '#64748B' },
        'slate.600': { value: '#475569' },
        'slate.700': { value: '#334155' },
        'slate.800': { value: '#1E293B' },
        'slate.900': { value: '#0F172A' },
        'slate.950': { value: '#020617' },
      },
      borders: {
        thin: { value: '0.1rem' },
        medium: { value: '0.15rem' },
        thick: { value: '0.2rem' },
      },
      fontSizes: {
        xs: { value: '1.2rem' },
        sm: { value: '1.4rem' },
        base: { value: '1.6rem' },
        lg: { value: '1.8rem' },
        xl: { value: '2rem' },
        '2xl': { value: '2.4rem' },
        '3xl': { value: '3rem' },
        '4xl': { value: '3.6rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
      lineHeights: {
        xs: { value: '1.6rem' },
        sm: { value: '2rem' },
        base: { value: '2.4rem' },
        lg: { value: '2.8rem' },
        xl: { value: '2.8rem' },
        '2xl': { value: '3.2rem' },
        '3xl': { value: '3.6rem' },
        '4xl': { value: '4rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
    },
  },
});
