import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  exclude: [],
  include: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  outdir: "styled-system",
  theme: {
    tokens: {
      colors: {
        white: { value: '#FFFFFF' },
        red600: { value: '#F43F5E' },
        green50: { value: '#F0FDF4' },
        green100: { value: '#DCFCE7' },
        green200: { value: '#BBF7D0' },
        green300: { value: '#86EFAC' },
        green400: { value: '#4ADE80' },
        green500: { value: '#22C55E' },
        green600: { value: '#16A34A' },
        green700: { value: '#15803D' },
        green800: { value: '#166534' },
        green900: { value: '#14532D' },
        green950: { value: '#052E16' },
        slate50: { value: '#F8FAFC' },
        slate100: { value: '#F1F5F9' },
        slate200: { value: '#E2E8F0' },
        slate300: { value: '#CBD5E1' },
        slate400: { value: '#94A3B8' },
        slate500: { value: '#64748B' },
        slate600: { value: '#475569' },
        slate700: { value: '#334155' },
        slate800: { value: '#1E293B' },
        slate900: { value: '#0F172A' },
        slate950: { value: '#020617' },
      },
      borders: {
        thin: { value: '0.1rem' },
        medium: { value: '0.15rem' },
        thick: { value: '0.2rem' },
      },
      fontSizes: {
        xs: { value: '1.2rem' },
        sm: { value: '1.4rem' },
        base: { value: '1.6rem' },
        lg: { value: '1.8rem' },
        xl: { value: '2rem' },
        '2xl': { value: '2.4rem' },
        '3xl': { value: '3rem' },
        '4xl': { value: '3.6rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
      lineHeights: {
        xs: { value: '1.6rem' },
        sm: { value: '2rem' },
        base: { value: '2.4rem' },
        lg: { value: '2.8rem' },
        xl: { value: '2.8rem' },
        '2xl': { value: '3.2rem' },
        '3xl': { value: '3.6rem' },
        '4xl': { value: '4rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
    },
  },
});
