import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  exclude: [],
  include: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  outdir: "styled-system",
  globalVars: {
    'sidebar-width': { value: '22.4rem' },
  },
  theme: {
    tokens: {
      radii: {
        sm: { value: '0.4rem' },
        md: { value: '0.8rem' },
        lg: { value: '1.2rem' },
        xl: { value: '1.6rem' },
        '2xl': { value: '2rem' },
        '3xl': { value: '2.4rem' },
        '4xl': { value: '3.2rem' },
      },
      colors: {
        white: { value: '#FFFFFF' },
        'red.100': { value: '#FFE2E2' },
        'red.600': { value: '#DC2626' },
        'green.10': { value: '#E6FAEB' },
        'green.20': { value: '#D9F7E0' },
        'green.30': { value: '#B0EFC0' },
        'green.40': { value: '#00CC33' },
        'green.50': { value: '#00B82E' },
        'green.60': { value: '#00A329' },
        'green.70': { value: '#009926' },
        'green.80': { value: '#007A1F' },
        'green.90': { value: '#005C17' },
        'green.100': { value: '#004712' },
        'void.10': { value: '#FAFAFA' },
        'void.20': { value: '#C3C3C3' },
        'void.30': { value: '#999999' },
        'void.40': { value: '#777777' },
        'void.50': { value: '#666666' },
        'void.60': { value: '#464646' },
        'void.70': { value: '#2C2C2C' },
        'void.80': { value: '#1E1E1E' },
        'void.90': { value: '#161616' },
        'void.100': { value: '#000000' },
      },
      borders: {
        thin: { value: '0.1rem' },
        medium: { value: '0.15rem' },
        thick: { value: '0.2rem' },
      },
      fontSizes: {
        xs: { value: '1.2rem' },
        sm: { value: '1.4rem' },
        base: { value: '1.6rem' },
        lg: { value: '1.8rem' },
        xl: { value: '2rem' },
        '2xl': { value: '2.4rem' },
        '3xl': { value: '3rem' },
        '4xl': { value: '3.6rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
      lineHeights: {
        xs: { value: '1.6rem' },
        sm: { value: '2rem' },
        base: { value: '2.4rem' },
        lg: { value: '2.8rem' },
        xl: { value: '2.8rem' },
        '2xl': { value: '3.2rem' },
        '3xl': { value: '3.6rem' },
        '4xl': { value: '4rem' },
        '5xl': { value: '4.8rem' },
        '6xl': { value: '6rem' },
        '7xl': { value: '7.2rem' },
        '8xl': { value: '9.6rem' },
        '9xl': { value: '12.8rem' },
      },
    },
  },
});
